🔖example: adapt
nyunAI/nyuntam pull request #8
Opened 2024-08-20 21:40 UTC by Abhrant

This PR adds the examples for Adapt.

2024-08-21 06:11 UTC, shwu-nyunai commented
any reasons, we have the examples using dockers? and if docker, why not with the cli directly?

2024-08-21 06:44 UTC, shwu-nyunai requested changes
Overall,
- do we need downstream tasks for the adaption algorithms? like, perf evals for finetuning and train time comparison if using dist training.
- any specific reasons why docker is the default flow? we can instead use the cli

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/image_segmentation/README.md
> +For this experiment we will be using the [CityScapes](https://www.kaggle.com/datasets/ipythonx/stanford-background-dataset) dataset. In this dataset we will only be using the "regions" as the segment
Do we have any formatting/modifications on this dataset to account only for the "regions" as segmentation? If yes, we can add details on the formatting step(s) too.

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/image_segmentation/README.md
> +dest_root : './.mmdet_cache'   #This saves the checkpoints and .py files for the model congigs and mmdet logs
nits -
spelling mistake in the comment. `model congigs -> model configs`

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/image_segmentation/README.md
Do we also have any evaluation or downstream steps after fine-tuning?

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/image_segmentation/config.yaml
> +dest_root : './.mmdet_cache'   #This saves the checkpoints and .py files for the model congigs and mmdet logs
nits.
same as above.

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/object_detection/README.md
1. Same as above, can this follow any evaluation or other downstream steps after ft? Or is it not needed? 
2. Should we be adding a comparison in the training time with/without DDP?

cc: @Arnav0400

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/object_detection/README.md
> +In this example, we'll be applying the LoRA technique to fine-tune the RTMDet model on the Face-Det dataset. The training process will be distributed across 2 GPUs using Distributed Data Parallel (DD
Can expand OOD.

```suggestion
In this example, we'll be applying the LoRA technique to fine-tune the RTMDet model on the Face-Det dataset. The training process will be distributed across 2 GPUs using Distributed Data Parallel (DDP) to maximize efficiency. LoRA's ability to introduce low-rank adaptations allows for targeted model updates, significantly reducing memory and computational requirements while increasing Out-of-Distribution (OOD) generalization performance. 
```

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/object_detection/README.md
> +LoRa decreases the toal trainable parameters of the model by freezing the original model weights and updating LoRA adapters only.
nits -
spelling mistake "total".
Lets do a sanity check on spelling mistakes and grammars across the examples.

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/object_detection/README.md
> +This is a sample log the experiment logs  :
```suggestion
This is a sample of the experiment logs  : 
```

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/text_generation/README.md
can we have an eval for this? some task that the dataset in concern increases the performance for. or not needed?

2024-08-21 06:44 UTC, shwu-nyunai commented on examples/adapt/text_generation/README.md
> +
is the tree correct for this algorithm? I see SUMM as the dir name for logs and o/p files.

2024-08-22 05:48 UTC, shwu-nyunai requested changes
also, what about the other comments? 
@Abhrant

2024-08-22 06:59 UTC, Abhrant commented on examples/adapt/text_generation/README.md
> +The output model will be stored in `user_data/jobs/Adapt/SUMM/` directory and the final directory structure will be:
done

2024-08-22 07:01 UTC, Abhrant commented
@shwu-nyunai , This workflow currently has the most suitable workflowfor adapt (the docker workflow) which can slo be done via the nyuntam repo. We are not showing the cli workflow here as far as I saw in other examples as well. So, These examples show the use of the nyuntam repo (and the way to setup the env is the docker)

2024-08-22 07:15 UTC, shwu-nyunai commented
> @shwu-nyunai , This workflow currently has the most suitable workflowfor adapt (the docker workflow) which can slo be done via the nyuntam repo. We are not showing the cli workflow here as far as I saw in other examples as well. So, These examples show the use of the nyuntam repo (and the way to setup the env is the docker)

What I meant is we can either do a docker flow example (which must use the nyuncli) or local installation; 
Vision examples uses docker and hence the example line out Nyun CLI flow. text generation lines out a local installation hence not docker dependent. Adapt should also either run with the cli or the local installation step right? Why the docker if cli does the same thing, in fact does it without any hassle of starting or maintaining the containers; 

cc: @Arnav0400 what is your opinion?

2024-08-22 10:26 UTC, Abhrant commented
@shwu-nyunai , The user doesn't know what the cli uses. These example shows how to use the nyuntam repo. The docker is just used to setup the environment and has no code. We can have a env workflow liek in text_gen but I think the docker is also fine and that is the most tested for now. So, I have kept that. 

cc @Arnav0400

2024-08-23 09:04 UTC, shwu-nyunai commented
closing in lieu #10

2024-08-23 09:04 UTC, closed without merging